[package]
name = "danker69/vec64"
version = "1.1.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["docs", ".vscode", ".github", "tests", "moonwave.toml"]
include = ["src", "LICENSE"]
homepage = "https://danker69.github.io/Vec64/"

[dependencies]
